### ISSUE TITLE
Compile to ES5 target

### ISSUE THREAD

**Issue by andersevenrud** [chriswoodle/async-dependency-graph#1]
Hi,

I've been using this for a while now and currently trying to get some stuff into production, but it seems that using latest Babel+Webpack is a bit of a pain when using packages that are not compiled down to ES5.

The issue is that I simply can't get Babel to transpile packages from `node_modules/` to ES5 for usage in my own packages. So the resulting bundles will contain stuff like `class Foo`, which is not supported in legacy browsers, which I unfortunately have to support.

So my question is, can you make your TS target ES5 ? I've tried to clone this repo and running the compilation but I've run into some issues (and I'm new to TS :blush:) ... and thought you'd be able to go thought this faster than I can make a PR.

Compiling down to ES5 for npm packages would probably be good in general :slightly_smiling_face: 

-- Anders

**Comment by chriswoodle** [comment]
Sure, no problem.
I've set it to target ES5. Just get 1.1.0 from npm.

**Comment by chriswoodle** [comment]
Let me know if you encounter any other problems, I'm using this in two production apps.

**Comment by andersevenrud** [comment]
Thanks for such a quick response and resolution. This pretty much solved all my problems. Now I just gotta polyfill all of the missing features and I can push a release.

Thank you so much for this :heart:
