### ISSUE TITLE
Getting "Cannot traverse graph due to no root node. The graph may be circular" when no nodes have been added

### ISSUE THREAD

**Issue by andersevenrud** [chriswoodle/async-dependency-graph#2]
Hi,

I was just messing around with some unit tests in a project that uses this library and it seems that if you don't actually add a node to a `Graph` you'll get the exception: `Cannot traverse graph due to no root node. The graph may be circular`.

Is this intentional ?

---

Example code:

```javascript
const {Graph} = require('async-dependency-graph');
const graph = new Graph();

graph
  .traverse()
  .then(() => console.info('Finished'))
  .catch(err => console.error(err))
```

Error:
```
/home/anders/Projects/async-dependency-graph/tmp/node_modules/async-dependency-graph/dist/graph.js:98
            throw new Error('Cannot traverse graph due to no root node. The graph may be circular');
            ^
Error: Cannot traverse graph due to no root node. The graph may be circular
    at Graph.traverse (/home/anders/Projects/async-dependency-graph/tmp/node_modules/async-dependency-graph/dist/graph.js:98:19)
    at Object.<anonymous> (/home/anders/Projects/async-dependency-graph/tmp/test.js:6:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by andersevenrud** [comment]
I expected it to just resolve the promise.

**Comment by chriswoodle** [comment]
Originally, I expected that if you didn't have any nodes in the graph you were more likely to be making some kind of mistake rather than intentionally trying to traverse an empty graph.

I do see how that in this case you would expect it to resolve, so it should probably do so.

**Comment by andersevenrud** [comment]
Nice :slightly_smiling_face:  I currently worked around this by just counting my collection before calling `traverse`, but that just feels wrong. So this change would be much appreciated :+1:

**Comment by chriswoodle** [comment]
Ok, should be resolved in https://github.com/chriswoodle/async-dependency-graph/commit/6439ecf429674eb1a5e01eb26bd4e3e73657c112

**Comment by andersevenrud** [comment]
Beautiful! Thanks :heart:
